package main

// preamble and handWritten are the parts of the notices file that no dependency
// graph can supply. They are kept here, next to the generator, so that
// regenerating never silently drops them — the same arrangement genwords uses
// for SOURCES.md.

const preamble = `# Third-party notices

<!-- Generated by tools/gennotices. Do not edit by hand; run ` + "`go run ./tools/gennotices`" + `. -->

The MIT licence in ` + "`LICENSE`" + ` at the root of this repository covers the original
work in this project: its source, its documentation, and the theme and word-list
files marked below as original.

It does **not** cover the third-party material listed here. Each item remains
under its own licence, reproduced in full. All of them are permissive, and all
of them require that their notice travel with any binary distribution — which is
why this file ships inside every release archive alongside the executable.

`

const handWritten = `
## Themes

Bundled themes live in ` + "`internal/theme/themes/*.toml`" + `. Each one adapted from
someone else's palette carries an ` + "`author`" + ` line naming its origin, and is used
here under that project's licence.

| Theme | Adapted from | Licence |
|---|---|---|
| ` + "`catppuccin-mocha`" + ` | [Catppuccin](https://github.com/catppuccin/catppuccin) | MIT |
| ` + "`dracula`" + ` | [Dracula](https://github.com/dracula/dracula-theme) | MIT |
| ` + "`everforest-dark`" + ` | [Everforest](https://github.com/sainnhe/everforest) | MIT |
| ` + "`gruvbox-dark`" + ` | [gruvbox](https://github.com/morhetz/gruvbox) | MIT |
| ` + "`nord`" + ` | [Nord](https://github.com/nordtheme/nord) | MIT |
| ` + "`rose-pine`" + ` | [Rosé Pine](https://github.com/rose-pine/rose-pine-theme) | MIT |
| ` + "`solarized-dark`" + ` | [Solarized](https://github.com/altercation/solarized) | MIT |
| ` + "`tokyo-night`" + ` | [Tokyo Night](https://github.com/enkia/tokyo-night-vscode-theme) | MIT |

` + "`ember-dark`" + `, ` + "`ember-light`" + `, ` + "`high-contrast`" + `, ` + "`matrix`" + ` and ` + "`terminal`" + ` are original to
this project and are covered by the root ` + "`LICENSE`" + `.

The visual design of the interface is inspired by
[Monkeytype](https://monkeytype.com), which is GPL-3.0. No Monkeytype code,
colour value or asset is used here — the influence is on layout and typography
only, which is not a licensable interest.

## Word lists

Full provenance, including the pinned upstream revisions, is in
` + "`internal/words/data/SOURCES.md`" + `.

| File | Source | Licence |
|---|---|---|
| ` + "`guesses{4,5,6}.txt`" + ` | [ENABLE1](https://github.com/dolph/dictionary) | Public domain |
| ` + "`answers{4,5,6}.txt`" + ` | [hermitdave/FrequencyWords](https://github.com/hermitdave/FrequencyWords), intersected with ENABLE1 | MIT |

ENABLE (Enhanced North American Benchmark Lexicon) was released into the public
domain by Alan Beale and Mendel Cooper. The frequency list is MIT-licensed and
derived from the OpenSubtitles 2018 corpus:

` + "```text" + `
Copyright (c) 2016 Hermit Dave

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
` + "```" + `

` + "`blocked.txt`" + ` and ` + "`profanity.txt`" + ` are hand-maintained here and covered by the
root ` + "`LICENSE`" + `.

## Trademarks

This project is not affiliated with, endorsed by, or connected to The New York
Times Company or any other rights holder in a similar game. Any such name is
used, where it appears at all, only to describe the kind of game this is.
`
