name = "rose pine"
author = "rosé pine"

[colors]
bg        = "#191724"
text      = "#e0def4"
accent    = "#ebbcba"
muted     = "#6e6a86"
error     = "#eb6f92"

correct   = "#31748f"
present   = "#f6c177"
absent    = "#26233a"

slot      = "#524f67"
key_face  = "#403d52"
key_spent = "#1f1d2e"

correct_text = "#e0def4"
